package cli

import (
	"bufio"
	"flag"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

var update = flag.Bool("update", false, "regenerate docs/reference")

const (
	docsDir      = "../../docs"
	referenceDir = "../../docs/reference"
)

func docsRoot() *cobra.Command {
	root := (&app{}).rootCommand()
	var disable func(*cobra.Command)
	disable = func(c *cobra.Command) {
		// No "Auto generated on <date>" footer, so the output is stable.
		c.DisableAutoGenTag = true
		for _, sub := range c.Commands() {
			disable(sub)
		}
	}
	disable(root)
	return root
}

func generateReference(t *testing.T, dir string) {
	t.Helper()
	prepend := func(string) string {
		return "<!-- Generated by `go test ./internal/cli -run TestReference -update`. Do not edit. -->\n\n"
	}
	link := func(name string) string { return name }
	if err := doc.GenMarkdownTreeCustom(docsRoot(), dir, prepend, link); err != nil {
		t.Fatal(err)
	}
}

// TestReferenceIsUpToDate keeps docs/reference in sync with the commands.
// Run with -update after changing commands or flags.
func TestReferenceIsUpToDate(t *testing.T) {
	if *update {
		if err := os.RemoveAll(referenceDir); err != nil {
			t.Fatal(err)
		}
		if err := os.MkdirAll(referenceDir, 0o755); err != nil {
			t.Fatal(err)
		}
		generateReference(t, referenceDir)
		return
	}

	fresh := t.TempDir()
	generateReference(t, fresh)
	want, _ := filepath.Glob(filepath.Join(fresh, "*.md"))
	got, _ := filepath.Glob(filepath.Join(referenceDir, "*.md"))
	if len(want) != len(got) {
		t.Fatalf("docs/reference has %d pages, the commands need %d; run: go test ./internal/cli -run TestReference -update", len(got), len(want))
	}
	for _, path := range want {
		expected, _ := os.ReadFile(path)
		actual, err := os.ReadFile(filepath.Join(referenceDir, filepath.Base(path)))
		if err != nil || string(expected) != string(actual) {
			t.Errorf("docs/reference/%s is out of date; run: go test ./internal/cli -run TestReference -update", filepath.Base(path))
		}
	}
}

var shellLine = regexp.MustCompile(`^(?:\$\s+)?(?:\./)?lmw(?:-linux|\.exe)?\s+(.*)$`)

// TestDocsOnlyUseRealCommandsAndFlags checks every `lmw ...` line in the
// code blocks of the README and docs/ against the actual command tree.
func TestDocsOnlyUseRealCommandsAndFlags(t *testing.T) {
	files := []string{"../../README.md"}
	err := filepath.WalkDir(docsDir, func(path string, d os.DirEntry, err error) error {
		if err == nil && !d.IsDir() && strings.HasSuffix(path, ".md") && !strings.Contains(path, "reference") {
			files = append(files, path)
		}
		return err
	})
	if err != nil {
		t.Fatal(err)
	}
	root := docsRoot()
	checked := 0
	for _, file := range files {
		for _, line := range codeLines(t, file) {
			m := shellLine.FindStringSubmatch(line)
			if m == nil {
				continue
			}
			checked++
			if problem := checkInvocation(root, m[1]); problem != "" {
				t.Errorf("%s: `%s`: %s", file, line, problem)
			}
		}
	}
	if checked < 20 {
		t.Errorf("only %d lmw invocations found in the docs; is the parser broken?", checked)
	}
}

// codeLines returns the lines inside shell code blocks (not ```text output
// blocks), cut at comments, pipes and command separators.
func codeLines(t *testing.T, path string) []string {
	t.Helper()
	f, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	var lines []string
	inCode, inShell := false, false
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "```") {
			inCode = !inCode
			lang := strings.TrimPrefix(line, "```")
			inShell = inCode && (lang == "bash" || lang == "sh" || lang == "shell" || lang == "powershell" || lang == "console")
			continue
		}
		if !inShell {
			continue
		}
		if !inCode {
			continue
		}
		for _, sep := range []string{" | ", " # ", " > ", " && ", " || "} {
			if i := strings.Index(line, sep); i >= 0 {
				line = line[:i]
			}
		}
		lines = append(lines, strings.TrimSpace(line))
	}
	return lines
}

func checkInvocation(root *cobra.Command, args string) string {
	cmd := root
	var flags []string
	positional := false
	for _, w := range splitWords(args) {
		switch {
		case strings.HasPrefix(w, "-") && w != "-":
			flags = append(flags, w)
		case !positional && findSub(cmd, w) != nil:
			cmd = findSub(cmd, w)
		default:
			// The first word that is not a subcommand ends the command path.
			positional = true
			if cmd == root {
				return "unknown command " + w
			}
		}
	}
	if cmd.HasSubCommands() && !cmd.Runnable() && !hasHelp(flags) && !(cmd == root && contains(flags, "--version")) {
		return "incomplete command; it needs a subcommand"
	}
	for _, w := range flags {
		name := strings.TrimLeft(strings.SplitN(w, "=", 2)[0], "-")
		if name == "help" || name == "h" || (cmd == root && name == "version") {
			continue
		}
		var found bool
		if strings.HasPrefix(w, "--") {
			found = cmd.Flags().Lookup(name) != nil || cmd.InheritedFlags().Lookup(name) != nil || root.PersistentFlags().Lookup(name) != nil
		} else {
			found = cmd.Flags().ShorthandLookup(name) != nil || root.PersistentFlags().ShorthandLookup(name) != nil
		}
		if !found {
			return "unknown flag " + w + " for `" + cmd.CommandPath() + "`"
		}
	}
	return ""
}

func findSub(cmd *cobra.Command, name string) *cobra.Command {
	for _, sub := range cmd.Commands() {
		if sub.Name() == name || contains(sub.Aliases, name) {
			return sub
		}
	}
	return nil
}

func hasHelp(words []string) bool { return contains(words, "--help") || contains(words, "-h") }

func contains(items []string, item string) bool {
	for _, v := range items {
		if v == item {
			return true
		}
	}
	return false
}

// splitWords splits a shell line on spaces, keeping quoted strings together.
func splitWords(line string) []string {
	var words []string
	var current strings.Builder
	quote := rune(0)
	for _, r := range line {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
			} else {
				current.WriteRune(r)
			}
		case r == '"' || r == '\'':
			quote = r
		case r == ' ' || r == '\t':
			if current.Len() > 0 {
				words = append(words, current.String())
				current.Reset()
			}
		default:
			current.WriteRune(r)
		}
	}
	if current.Len() > 0 {
		words = append(words, current.String())
	}
	return words
}

func TestCheckInvocation(t *testing.T) {
	root := docsRoot()
	ok := []string{"feed -n 20 --json", "auth import --browser firefox", "post draft My idea --tone technical", "--version", "auth --help", "-v me"}
	bad := []string{"feeds", "feed --nope", "auth", "post publish --dry-run"}
	for _, args := range ok {
		if problem := checkInvocation(root, args); problem != "" {
			t.Errorf("%q: unexpected problem %q", args, problem)
		}
	}
	for _, args := range bad {
		if checkInvocation(root, args) == "" {
			t.Errorf("%q: expected a problem", args)
		}
	}
	names := []string{}
	for _, c := range root.Commands() {
		names = append(names, c.Name())
	}
	sort.Strings(names)
	if len(names) < 8 {
		t.Errorf("unexpected command list %v", names)
	}
}

var (
	mdLink  = regexp.MustCompile(`\]\(([^)\s]+)\)`)
	heading = regexp.MustCompile(`(?m)^#{1,6}\s+(.+)$`)
	slugBad = regexp.MustCompile(`[^\p{L}\p{N}\s_-]`)
)

// githubSlug reproduces GitHub's heading anchors.
func githubSlug(title string) string {
	title = strings.ToLower(strings.TrimSpace(title))
	title = slugBad.ReplaceAllString(title, "")
	return strings.ReplaceAll(title, " ", "-")
}

// TestDocsLinksResolve checks that relative links point to existing files
// and, when they have one, to an existing heading.
func TestDocsLinksResolve(t *testing.T) {
	var files []string
	_ = filepath.WalkDir(docsDir, func(path string, d os.DirEntry, err error) error {
		if err == nil && !d.IsDir() && strings.HasSuffix(path, ".md") {
			files = append(files, path)
		}
		return err
	})
	files = append(files, "../../README.md")
	anchors := func(path string) map[string]bool {
		raw, _ := os.ReadFile(path)
		set := map[string]bool{}
		inCode := false
		for _, line := range strings.Split(string(raw), "\n") {
			if strings.HasPrefix(strings.TrimSpace(line), "```") {
				inCode = !inCode
			}
			if m := heading.FindStringSubmatch(line); m != nil && !inCode {
				set[githubSlug(m[1])] = true
			}
		}
		return set
	}
	checked := 0
	for _, file := range files {
		raw, _ := os.ReadFile(file)
		for _, m := range mdLink.FindAllStringSubmatch(string(raw), -1) {
			target := m[1]
			if strings.Contains(target, "://") || strings.HasPrefix(target, "mailto:") {
				continue
			}
			path, anchor, _ := strings.Cut(target, "#")
			resolved := file
			if path != "" {
				resolved = filepath.Join(filepath.Dir(file), path)
			}
			checked++
			if _, err := os.Stat(resolved); err != nil {
				t.Errorf("%s: link to missing file %s", file, target)
				continue
			}
			if anchor != "" && strings.HasSuffix(resolved, ".md") && !anchors(resolved)[anchor] {
				t.Errorf("%s: link to missing heading %s", file, target)
			}
		}
	}
	if checked < 30 {
		t.Errorf("only %d links checked; is the parser broken?", checked)
	}
}

func TestGithubSlug(t *testing.T) {
	cases := map[string]string{
		"Step 1. Install lmw":        "step-1-install-lmw",
		"Method 1: HAR file":         "method-1-har-file",
		"Client hints (`sec-ch-ua`)": "client-hints-sec-ch-ua",
		"If LinkedIn pushes back":    "if-linkedin-pushes-back",
		"What `auth import` does":    "what-auth-import-does",
	}
	for title, want := range cases {
		if got := githubSlug(title); got != want {
			t.Errorf("githubSlug(%q) = %q, want %q", title, got, want)
		}
	}
}
